# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecnewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(verbose_name='published date')),
                ('tag', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('en_text', models.TextField(verbose_name='original English text')),
                ('cn_text', models.TextField(verbose_name='Chinese summary')),
            ],
        ),
    ]
