# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secnewsitem',
            name='img_link',
            field=models.TextField(default='', verbose_name='illustration link'),
        ),
        migrations.AlterField(
            model_name='secnewsitem',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='secnewsitem',
            name='en_text',
            field=models.TextField(default='', verbose_name='original English text'),
        ),
    ]
