# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secnews', '0002_auto_20170830_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secnewsitem',
            name='img_link',
            field=models.URLField(default='', verbose_name='illustration link'),
        ),
    ]
